// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTPqyfg4h8FvOdxD8kh-pjZD-4OwOWWhc',
    appId: '1:1048375441547:web:a72a962b3052bdfc367c8e',
    messagingSenderId: '1048375441547',
    projectId: 'petrush-f03e1',
    authDomain: 'petrush-f03e1.firebaseapp.com',
    storageBucket: 'petrush-f03e1.appspot.com',
    measurementId: 'G-9XMZV48T6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx_-Gf4f4k3vrTwVyD_UtmAGBOTn6FPeE',
    appId: '1:1048375441547:android:fcf493e4d00934b4367c8e',
    messagingSenderId: '1048375441547',
    projectId: 'petrush-f03e1',
    storageBucket: 'petrush-f03e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnps_AxH6kt30BEEC_Rlws5fyWrYJXn74',
    appId: '1:1048375441547:ios:d2eb1999d651262d367c8e',
    messagingSenderId: '1048375441547',
    projectId: 'petrush-f03e1',
    storageBucket: 'petrush-f03e1.appspot.com',
    iosClientId: '1048375441547-3lh0o9jqflqk1uji0qragmu6kp6cqeml.apps.googleusercontent.com',
    iosBundleId: 'com.example.edwardsPet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnps_AxH6kt30BEEC_Rlws5fyWrYJXn74',
    appId: '1:1048375441547:ios:d2eb1999d651262d367c8e',
    messagingSenderId: '1048375441547',
    projectId: 'petrush-f03e1',
    storageBucket: 'petrush-f03e1.appspot.com',
    iosClientId: '1048375441547-3lh0o9jqflqk1uji0qragmu6kp6cqeml.apps.googleusercontent.com',
    iosBundleId: 'com.example.edwardsPet',
  );
}
